#!/bin/bash

bsize=$(ls -l "$1" | awk {'print $5'})
sqlite3 "$1" vacuum &>/dev/null
sqlite3 "$1" reindex &>/dev/null
asize=$(ls -l "$1" | awk {'print $5'})
dsize=$(echo "scale=2; ($bsize-$asize)/1048576" | bc)
echo "$1" reduced by $dsize Mbytes
