#!/bin/bash
VERS="@VERSION@"

#
#	$XDG_CONFIG_HOME should be mapped to $HOME/.config
# some users may have modified it to a custom location so honor that
#

XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"	

#
# read in config file
#

config="$XDG_CONFIG_HOME/profile-cleaner.conf"	# profile-cleaner config

if [[ -f $config ]]; then
	. $config
else
	echo "#" > $config 
	echo "# $HOME/.config/profile-cleaner.conf" >> $config 
	echo "#" >> $config 
	echo >> $config 
	echo "# Define the background of your terminal theme here." >> $config 
	echo "# A setting of "dark" will produce colors that nicely contrast a dark background." >> $config 
	echo "#  setting of "light" will produce colors that nicely contrast a light background." >> $config 
	echo "COLORS=dark" >> $config 
	echo "#COLORS=light" >> $config 
fi

[[ -z "$COLORS" ]] && COLORS="dark"	# if users screws up syntax, default to dark
[[ "$COLORS" = "dark" ]] &&  export BLD="\e[01m" RED="\e[01;31m" GRN="\e[01;32m" YLW="\e[01;33m" NRM="\e[00m"
[[ "$COLORS" = "light" ]] && export BLD="\e[01m" RED="\e[00;31m" GRN="\e[00;32m" YLW="\e[00;34m" NRM="\e[00m"

echo -e "${RED}profile-cleaner v$VERS${NRM}"
echo

dep_check() {
  # Although the package manager should handle these deps, this function is a sanity check for users.
  command -v sqlite3 >/dev/null 2>&1 || { echo "I require sqlite3 but it's not installed. Aborting." >&2; exit 1; }
  command -v bc >/dev/null 2>&1 || { echo "I require bc but it's not installed. Aborting." >&2; exit 1; }
  command -v find >/dev/null 2>&1 || { echo "I require find but it's not installed. Aborting." >&2; exit 1; }
  command -v parallel >/dev/null 2>&1 || { echo "I require parallel but it's not installed. Aborting." >&2; exit 1; }
}

do_clean() {
	echo -en "${GRN} Cleaning${NRM} ${1##*/}"
	bsize=$(du -b "$1" | cut -f 1)
	
	sqlite3 "$1" vacuum
	sqlite3 "$1" reindex
	
	asize=$(du -b "$1" | cut -f 1)
	dsize=$(echo "scale=2; ($bsize-$asize)/1048576" | bc)
	echo -e "$(tput cr)$(tput cuf 46) ${GRN}done${NRM}  -${YLW}${dsize}${NRM} Mbytes"
}

do_clean_parallel () {
	[[ ${#toclean[@]} -eq 0 ]] && cleanedsize=0 && return 1
	bsize=$(du -b -c "${toclean[@]}" | tail -n 1 | cut -f 1)
	
	SHELL=/bin/bash parallel --gnu -k do_clean ::: "${toclean[@]}" 2>/dev/null
	
	asize=$(du -b -c "${toclean[@]}" | tail -n 1 | cut -f 1)
	cleanedsize=$(echo "scale=2; ($bsize-$asize)/1048576" | bc)
}

find_dbs() {
	# fill toclean array by looking for SQLite files in each input directory
	toclean=()
	while read i; do
		toclean+=("${i}")
	done < <( find -L "$@" -maxdepth 2 -type f -print0 2>/dev/null | xargs -0 file -e ascii | sed -n -e "s/:.*SQLite.*//p" )
}

do_chromebased() {
	[[ -h "$prepath" ]] && profilepath=$(readlink $prepath) || profilepath="$prepath"
	[[ ! -d "$profilepath" ]] &&	echo -e ${RED}"Error: no profile directory for $name found."${NRM} &&	exit 1
	echo -e " ${YLW}Cleaning profile for $name${NRM}"
	find_dbs "$profilepath"
	do_clean_parallel
	echo
	echo -e " ${BLD}Profile(s) for $name reduced by ${YLW}${cleanedsize}${NRM} ${BLD}Mbytes.${NRM}"
}

do_xulbased() {
	if [[ -h "$prepath" ]]; then
		profilepath=$(readlink $prepath)
	else
		profilepath="$prepath"
	fi

	if [[ ! -d "$profilepath" ]]; then
		echo -e ${RED}"Error: cannot locate $profilepath"${NRM}
		echo -e ${BLD}"This is the default path for $name and where $0 expects to find it."${NRM}
		exit 1
	fi

	[[ ! -f $profilepath/profiles.ini ]] && echo -e ${RED}"Error: cannot locate $profilepath/profiles.ini to determine names of profiles for $name."${NRM} &&	exit 1

	#
	# build an array correcting for rel and abs paths therein
	# while read will read line-by-line and will tolerate spaces whereas a for loop will not
	#

	index=0
	while read line; do
		if [[ ! -d "$profilepath/$line" ]]; then
			finalArr[index]="$line"
		else
			finalArr[index]="$profilepath/$line"
		fi
		index=$index+1
	done < <(grep '[P,p]'ath "$profilepath/profiles.ini" | sed -e 's/[P,p]ath=//' -e 's/\r//' )

	echo -e " ${YLW}Cleaning profile for $name${NRM}"
	find_dbs "${finalArr[@]}"
	do_clean_parallel
	echo
	echo -e " ${BLD}Profile(s) for $name reduced by ${YLW}${cleanedsize}${NRM} ${BLD}Mbytes.${NRM}"
}

do_dbbased() {
	[[ -h "$prepath" ]] && profilepath=$(readlink $prepath) || profilepath="$prepath"
	[[ ! -d "$profilepath" ]] &&	echo -e ${RED}"Error: no profile directory for $name found."${NRM} &&	exit 1
	echo -e " ${YLW}Cleaning profile for $name${NRM}"
	find_dbs "${profilepath}"
	do_clean_parallel
	echo
	echo -e " ${BLD}Profile(s) for $name reduced by ${YLW}${cleanedsize}${NRM} ${BLD}Mbytes.${NRM}"
}

do_paths() {
	profilepaths=()
	for profilepath in "$@"; do
		[[ -d "$profilepath" ]] && profilepaths+=("$profilepath")
	done
	find_dbs "${profilepaths[@]}"
	do_clean_parallel
	echo
	echo -e " ${BLD}Profile(s) for $name reduced by ${YLW}${cleanedsize}${NRM} ${BLD}Mbytes.${NRM}"
}

export -f do_clean
dep_check

case "$1" in
	C|c)
		name="chromium" ; export name
		prepath="$XDG_CONFIG_HOME"/$name
		do_chromebased
		exit 0
		;;
	Gc|gC|GC|gc)
		name="google-chrome" ; export name
		prepath="$XDG_CONFIG_HOME"/$name
		do_chromebased
		exit 0
		;;	
	F|f)
		name="firefox"; export name
		prepath=$HOME/.mozilla/$name
		do_xulbased
		exit 0
		;;
	CK|cK|Ck|ck)
		name="conkeror"; export name
		prepath=$HOME/.conkeror.mozdev.org/$name
		do_xulbased
		exit 0
		;;
	H|h)
		name="aurora"; export name
		prepath=$HOME/.mozilla/aurora
		do_xulbased
		exit 0
		;;
	T|t)
		name="thunderbird"; export name
		prepath=$HOME/.$name
		do_xulbased
		exit 0
		;;
	M|m)
		name="midori"; export name
		prepath="$XDG_CONFIG_HOME"/$name
		do_dbbased
		exit 0
		;;
	Q|q)
		name="qupzilla"; export name
		prepath=$HOME/.$name/profiles
		do_dbbased
		exit 0
		;;
	P|p)
		name="paths"; export name
		shift
		do_paths "$@"
		exit 0
		;;
	*)
		echo -e " ${BLD}$0 ${NRM}${GRN}{c|ck|f|gc|h|m|t|q|p}${NRM}"
		echo
		echo -e "  ${BLD}c) ${GRN}C${NRM}${BLD}hromium"${NRM}
		echo -e " ${BLD}ck) ${GRN}C${NRM}${BLD}on${GRN}k${NRM}${BLD}eror"${NRM}
		echo -e "  ${BLD}f) ${GRN}F${NRM}${BLD}irefox"${NRM}
		echo -e " ${BLD}gc) ${GRN}G${NRM}${BLD}oogle ${GRN}C${NRM}${BLD}hrome"${NRM}
		echo -e "  ${BLD}h) ${GRN}H${NRM}${BLD}eftig's Aurora"${NRM}
		echo -e "  ${BLD}m) ${GRN}M${NRM}${BLD}idori"${NRM}
		echo -e "  ${BLD}t) ${GRN}T${NRM}${BLD}hunderbird"${NRM}
		echo -e "  ${BLD}q) ${GRN}Q${NRM}${BLD}upZilla"${NRM}
		echo -e "  ${BLD}p) ${GRN}P${NRM}${BLD}aths"${NRM}
		exit 0
		;;
esac
